### ISSUE TITLE
Parallex grey border on home

### ISSUE THREAD

**Issue by jeroen-van-dijk** [antonderegt/max30#3]
vue parallex seems to add a grey border. Can't find where the css is adding it and how I could disable it

**Comment by jeroen-van-dijk** [comment]
Same for underline of text-field in location search on home

**Comment by antonderegt** [comment]
When I add a src="xxx" to v-parallax, the border disappears.

**Comment by antonderegt** [comment]
Fixed with commit: 30635be3277b222f0f0cf25552321ac0e25e727a

It uses a random image at the moment, should be changed.
